# Cure data

## Dependencies and setup

```{r}
library(tidyverse)
library(cowplot)
library(RColorBrewer)
library(khroma)
library(rstatix)
library(knitr)
library(kableExtra)
library(viridis)
# library(webshot2)
```

```{r}
# Build relative path from R's working directory to what is actually the working
# directory for this experiment.
experiment_slug <- "2026-03-02-combined-mutualism-constraint"
working_directory <- paste(
  "experiments",
  experiment_slug,
  sep = "/"
)
```

```{r}
# Use the cowplot theme as our default for ggplots
theme_set(theme_cowplot())
# Create directory to save plots
plot_dir <- paste(
  working_directory,
  "plots",
  sep = "/"
)
dir.create(
  plot_dir,
  showWarnings = FALSE
)
```

### Load and preprocess data

```{r}
tasks <- c("NOT", "NAND", "OR_NOT", "AND", "OR", "AND_NOT", "NOR", "XOR", "EQU")
max_pop_size <- 100 * 100
threshold <- 0.025 * max_pop_size
```

Load summary data.

```{r}
summary_data_path <- paste(
  working_directory,
  "cure-data",
  "summary.csv",
  sep = "/"
)
cure_summary_data <- read_csv(summary_data_path)
# Do any universal preprocessing
cure_summary_data <- cure_summary_data %>%
  mutate(
    seed = as.factor(SEED),
    CURE = as.logical(CURE),
    CURE_UPDATES = as.factor(CURE_UPDATES)
  ) %>%
  mutate(
    task_credit = paste0(
      "H", HOST_ONLY_FIRST_TASK_CREDIT,
      "S", SYM_ONLY_FIRST_TASK_CREDIT
    ),
    sym_condition = case_when(
      START_MOI == "0" ~ "no-syms",
      START_MOI == "1" & HEALTH_TYPE == "parasite" ~ "parasite",
      START_MOI == "1" & HEALTH_TYPE == "mutualist" ~ "mutualist",
      .default = "unknown" # precaution against unexpected parameterizations
    ),
    extinct_syms = OrgCounts_hosted_sym_count == 0
  ) %>%
  mutate(
    cure_condition = case_when(
      sym_condition == "no-syms" ~ "No symbionts",
      CURE & CURE_UPDATES == 150000 ~ "75%",
      CURE & CURE_UPDATES == 100000 ~ "50%",
      CURE & CURE_UPDATES == 50000 ~ "25%",
      !CURE ~ "Not cured",
      .default = "unknown"
    )
  ) %>%
  filter( # Filter out extra no symbiont runs
    (sym_condition != "no-syms") |
    (sym_condition == "no-syms" & SEED < 160200)
  ) %>%
  mutate(
    cure_condition = as.factor(cure_condition),
    unique_id = paste0(
      sym_condition, "_", cure_condition, "_", SEED
    )
  ) %>%
  mutate(
    unique_id = as.factor(unique_id)
  )

```

Load time series data

```{r}
time_data_path <- paste(
  working_directory,
  "cure-data",
  "time_series.csv",
  sep = "/"
)
time_data <- read_csv(time_data_path)

# Do any universal preprocessing
time_data <- time_data %>%
    mutate(
    seed = as.factor(SEED),
    CURE = as.logical(CURE),
    CURE_UPDATES = as.factor(CURE_UPDATES)
  ) %>%
  mutate(
    sym_condition = case_when(
      START_MOI == "0" ~ "no-syms",
      START_MOI == "1" & HEALTH_TYPE == "parasite" ~ "parasite",
      START_MOI == "1" & HEALTH_TYPE == "mutualist" ~ "mutualist",
      .default = "unknown" # precaution against unexpected parameterizations
    ),
    extinct_syms = OrgCounts_hosted_sym_count == 0,
  ) %>%
    mutate(
    cure_condition = case_when(
      sym_condition == "no-syms" ~ "No symbionts",
      CURE & CURE_UPDATES == 150000 ~ "75%",
      CURE & CURE_UPDATES == 100000 ~ "50%",
      CURE & CURE_UPDATES == 50000 ~ "25%",
      !CURE ~ "Not cured",
      .default = "unknown"
    )
  ) %>%
  filter( # Filter out extra no symbiont runs
    (sym_condition != "no-syms") |
    (sym_condition == "no-syms" & SEED < 160200)
  ) %>%
  mutate(
    cure_condition = as.factor(cure_condition),
    unique_id = paste0(
      sym_condition, "_", cure_condition, "_", SEED
    )
  ) %>%
  mutate(
    unique_id = as.factor(unique_id)
  )
```

Host complexity data

```{r}
host_over_time_parent_task_data <- time_data %>%
  select(
    unique_id,
    sym_condition,
    cure_condition,
    update,
    CurUpdate_AND_NOT_in_host_parent_org_counts,
    CurUpdate_AND_in_host_parent_org_counts,
    CurUpdate_EQU_in_host_parent_org_counts,
    CurUpdate_NAND_in_host_parent_org_counts,
    CurUpdate_NOR_in_host_parent_org_counts,
    CurUpdate_NOT_in_host_parent_org_counts,
    CurUpdate_OR_NOT_in_host_parent_org_counts,
    CurUpdate_OR_in_host_parent_org_counts,
    CurUpdate_XOR_in_host_parent_org_counts
  ) %>%
  pivot_longer(
    c(
      CurUpdate_AND_NOT_in_host_parent_org_counts,
      CurUpdate_AND_in_host_parent_org_counts,
      CurUpdate_EQU_in_host_parent_org_counts,
      CurUpdate_NAND_in_host_parent_org_counts,
      CurUpdate_NOR_in_host_parent_org_counts,
      CurUpdate_NOT_in_host_parent_org_counts,
      CurUpdate_OR_NOT_in_host_parent_org_counts,
      CurUpdate_OR_in_host_parent_org_counts,
      CurUpdate_XOR_in_host_parent_org_counts
    ),
    names_to = "task",
    values_to = "task_in_parent_count"
  ) %>%
  mutate(
    task = str_replace(task, "CurUpdate_", "")
  ) %>%
  mutate(
    task = str_replace(task, "_in_host_parent_org_counts", "")
  ) %>%
  mutate(
    task_completed_by_parent = task_in_parent_count >= threshold,
    task = factor(
      task,
      levels = tasks,
      labels = tasks
    )
  ) %>%
  mutate(
    task_complexity = case_when(
      task == "NOT" ~ 1,
      task == "NAND" ~ 1,
      task == "OR_NOT" ~ 2,
      task == "AND" ~ 2,
      task == "OR" ~ 3,
      task == "AND_NOT" ~ 3,
      task == "NOR" ~ 4,
      task == "XOR" ~ 4,
      task == "EQU" ~ 5,
      .default = -1
    )
  )

host_parent_tasks_all_time_by_task <- host_over_time_parent_task_data %>%
  group_by(
    unique_id,
    sym_condition,
    cure_condition,
    task
  ) %>%
  summarize(
    n = n(),
    parent_task_completed_ever = any(task_completed_by_parent)
  ) %>%
  ungroup() %>%
  group_by(
    unique_id,
    sym_condition,
    cure_condition,
    task
  ) %>%
  summarize(
    n = n(),
    parent_tasks_completed_ever = sum(parent_task_completed_ever == TRUE)
  )
```

Additionally, summarize by task complexity level.

```{r}
host_max_task_complexity_data <- host_over_time_parent_task_data %>%
  group_by(
    unique_id,
    sym_condition,
    cure_condition,
    task,
    task_complexity
  ) %>%
  summarize(
    n = n(),
    parent_task_completed_ever = any(task_completed_by_parent)
  ) %>%
  ungroup() %>%
  # This filter works fine because all replicates start with a task
  filter(
    parent_task_completed_ever
  ) %>%
  group_by(
    unique_id,
    sym_condition,
    cure_condition
  ) %>%
  summarize(
    max_task_complexity = max(task_complexity)
  ) %>%
  mutate(
    sym_condition = factor(
      sym_condition,
      levels = c(
        "no-syms",
        "parasite",
        "mutualist"
      )
    )
  )

host_max_task_complexity_over_time_data <- host_over_time_parent_task_data %>%
  # This filter works fine because all replicates start with a task
  filter(
    task_completed_by_parent
  ) %>%
  group_by(
    unique_id,
    cure_condition,
    sym_condition,
    update
  ) %>%
  summarize(
    max_task_complexity = max(task_complexity)
  )
```

## Host task complexity over time

```{r}
# write_csv(
#   host_max_task_complexity_over_time_data,
#   paste(
#     working_directory,
#     "cure_host_max_task_complexity_over_time.csv",
#     sep = "/"
#   ),
# )

cure_host_max_task_complexity_over_time_plt <- host_max_task_complexity_over_time_data %>%
  # filter(
  #   update %% 10000 == 0
  # ) %>%
  ggplot(
    aes(
      x = update,
      y = max_task_complexity,
      color = cure_condition,
      fill = cure_condition
    )
  ) +
  stat_summary(fun = "mean", geom = "line") +
  stat_summary(
    fun.data = "mean_cl_boot",
    fun.args = list(conf.int = 0.99),
    geom = "ribbon",
    alpha = 0.2,
    linetype = 0
  ) +
  scale_color_bright() +
  scale_fill_bright() +
  # scale_fill_manual(values = color_pal) +
  # scale_color_manual(values = color_pal) +
  scale_y_continuous(
    limits = c(0, 5.1)
  ) +
  labs(
    x = "Updates",
    y = "Host function complexity",
    color = "Cure",
    fill = "Cure"
  ) +
  theme(
    legend.position = "bottom"
  )

ggsave(
  file = paste(
    plot_dir,
    "cure_host_max_task_complexity_over_time_plt.pdf",
    sep = "/"
  ),
  plot = cure_host_max_task_complexity_over_time_plt,
  width = 6,
  height = 4
)
```